Vagrant.configure("2") do |config|

	config.vm.define "bullseye-arm64" do |machine|
  		machine.vm.box = "./output/bullseye-arm64.box"
  		machine.vm.provider "parallels" do |prl|
  			prl.name = "bullseye-arm64"
  			prl.update_guest_tools = false
  			prl.linked_clone = false
  			prl.customize [ "set", "bullseye-arm64", "--cpus", 1 ]
  			prl.customize [ "set", "bullseye-arm64", "--memsize", 1024 ]
  			prl.customize [ "set", "bullseye-arm64", "--distribution", "debian" ]
  			prl.customize [ "set", "bullseye-arm64", "--time-sync", "on" ]
  			prl.customize [ "set", "bullseye-arm64", "--sync-vm-hostname", "on" ]
  		end
  	end

end
