Vagrant.configure("2") do |config|

	config.vm.define "base" do |machine|
  		machine.vm.box = "./output/base-parallels-arm64.box"
  		machine.vm.provider "parallels" do |prl|
  			prl.name = "base-parallels-arm64"
  			prl.update_guest_tools = false
  			prl.linked_clone = false
  			prl.customize [ "set", "base-parallels-arm64", "--cpus", 1 ]
  			prl.customize [ "set", "base-parallels-arm64", "--memsize", 1024 ]
  			prl.customize [ "set", "base-parallels-arm64", "--distribution", "debian" ]
  			prl.customize [ "set", "base-parallels-arm64", "--time-sync", "on" ]
  		end
  	end

end
